// This source code is provided "as is" without warranty of any kind, either express or implied. Use at your own risk.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "../VARIDCommon.ush"

Texture2D InSceneColorSRV;
float2 InFrequency;
float2 InAmplitude;

void MainPS
(
    in noperspective float4 UVAndScreenPos : TEXCOORD0,
    out float4 OutColor : SV_Target0
)
{
    float2 Offset = VARID_Wave_AsymmetricTriangle_Randomized(View.RealTime, InFrequency, InAmplitude, float2(0.99f, 0.99f), 0.9);
    float2 JitteredUV = UVAndScreenPos.xy + Offset;
    OutColor = InSceneColorSRV.Sample(View.SharedBilinearClampedSampler, JitteredUV);
}