// This source code is provided "as is" without warranty of any kind, either express or implied. Use at your own risk.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "../VARIDCommon.ush"

Texture2D InSceneColorSRV;
float2 InNormalizedGazePosition;
float InAspectRatio;
float InRadius;
float InBlurStrength;
float InMaxMipLevel;

void MainPS
(
    in noperspective float4 UVAndScreenPos : TEXCOORD0,
	out float4 OutColor : SV_Target0
)
{
    float2 ViewportUV = UVAndScreenPos.xy; //BufferUVToViewportUV(UVAndScreenPos.xy);
    float2 NDC = ConvertFrom0to1ToMinus1to1(ViewportUV);
    float2 Delta = NDC - InNormalizedGazePosition;
    Delta.x *= InAspectRatio;
    float DistanceFromGazePoint = length(Delta);
    float Mask = 1.0 - smoothstep(0.0, InRadius, DistanceFromGazePoint);

    float ScaledBlurStrength = clamp(Mask * InBlurStrength, 0.0, InMaxMipLevel); // scaled to fit the number of mip levels available
    OutColor = InSceneColorSRV.SampleLevel(View.SharedTrilinearClampedSampler, UVAndScreenPos.xy, ScaledBlurStrength);
}