// This source code is provided "as is" without warranty of any kind, either express or implied. Use at your own risk.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "../VARIDCommon.ush"

void MainPS
(
    in noperspective float4 UVAndScreenPos : TEXCOORD0,
	out float4 OutColor : SV_Target0
)
{    
    float2 ViewportUV = BufferUVToViewportUV(UVAndScreenPos.xy);
    // display a UV map (red and green gradient)
    OutColor = float4(ViewportUV.x, ViewportUV.y, 0, 1);
}