// This source code is provided "as is" without warranty of any kind, either express or implied. Use at your own risk.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "../VARIDCommon.ush"

float2 InTexelSize;
SamplerState InSampler;
Texture2D<float4> InSRV;
RWTexture2D<float4> OutUAV;

[numthreads(8, 8, 1)]
void MainCS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    float2 UV = InTexelSize * (float2(DispatchThreadID.xy) + 0.5f);

    // Compute shaders do not have implicit texture gradients.
    // SampleLevel gives an explicit mip level and is SM5-compatible.
    float4 OutColor = InSRV.SampleLevel(InSampler, UV, 0.0f);

    OutUAV[DispatchThreadID.xy] = OutColor;
}